### ISSUE TITLE
New project is broken on setup (SyntaxError: Unexpected identifier 'assert')

### ISSUE THREAD

**Issue by randomsnowflake** [batosai/adonis-starter-kit#3]
1.: In the project setup description, it needs to point out to run an `npm install` before executing the migrations

2.: Running the migration fails, without any indication why: 

```
% node ace migration:run
(node:63741) [DEP0180] DeprecationWarning: fs.Stats constructor is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)

   SyntaxError: Unexpected identifier 'assert'
 
   at (syntax error) SyntaxError: Unexpected identifier 'assert'
```

My env: 
```
node -v
v22.7.0

uname
Darwin
```

**Comment by batosai** [comment]
Hi @randomsnowflake .

1. fixed
2. it's ok for me

**Comment by randomsnowflake** [comment]
Thanks for your reply. 

I think 1) actually resolved my issue. It is essential to initialize the project with `npm init`. Cloning the project and then executing the other commands results in errors during database migration or seeding.
